__title__ = 'gpm-player'
__description__ = 'Multi platform and text based Google-Play-Music player'
__url__ = 'http://github.com/johejo/gpm-player'
__version__ = '0.1.2'
__author__ = 'Mitsuo Heijo'
__author_email__ = 'mitsuo_h@outlook.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Mitsuo Heijo'
